---
title: "Cubist Exploration"
author: "Chirag Kumar and Guillermo Podesta"
output:
  html_notebook:
    toc: True
    theme: united
---


```{r prep_workspace, echo=TRUE}
require(ggplot2)
require(dplyr)
require(Cubist)
require(caret)
set.seed(108)
```

# Cubist Exploration with Simulated Data

```{r Cubist_test_1, echo=TRUE}
# Create two features, x1 and x2
x1 <- seq(from = 1, to = 90, by = 1)
x2 <- seq(from = 10, to = 900, by = 10)

grid_1 <- expand.grid(x1, x2) # Turn x1 and x2 into a grid
colnames(grid_1) <- c("x1", "x2") # Rename columns

# Divide grid into 9 equally sized regions
grid_1$region_num <- rep(NA, length(x1) * length(x2))

grid_1$region_num[(grid_1$x1 >= 1 & grid_1$x1 <= 30) & (grid_1$x2 >= 10 & grid_1$x2 <= 300)] <- 1
grid_1$region_num[(grid_1$x1 >= 31 & grid_1$x1 <= 60) & (grid_1$x2 >= 10 & grid_1$x2 <= 300)] <- 2
grid_1$region_num[(grid_1$x1 >= 61 & grid_1$x1 <= 90) & (grid_1$x2 >= 10 & grid_1$x2 <= 300)] <- 3

grid_1$region_num[(grid_1$x1 >= 1 & grid_1$x1 <= 30) & (grid_1$x2 >= 310 & grid_1$x2 <= 600)] <- 4
grid_1$region_num[(grid_1$x1 >= 31 & grid_1$x1 <= 60) & (grid_1$x2 >= 310 & grid_1$x2 <= 600)] <- 5
grid_1$region_num[(grid_1$x1 >= 61 & grid_1$x1 <= 90) & (grid_1$x2 >= 310 & grid_1$x2 <= 600)] <- 6

grid_1$region_num[(grid_1$x1 >= 1 & grid_1$x1 <= 30) & (grid_1$x2 >= 610 & grid_1$x2 <= 900)] <- 7
grid_1$region_num[(grid_1$x1 >= 31 & grid_1$x1 <= 60) & (grid_1$x2 >= 610 & grid_1$x2 <= 900)] <- 8
grid_1$region_num[(grid_1$x1 >= 61 & grid_1$x1 <= 90) & (grid_1$x2 >= 610 & grid_1$x2 <= 900)] <- 9

table(grid_1$region_num, useNA = "always")
```

```{r plot_regions_1, echo=TRUE}
ggplot2::ggplot(data = grid_1) +
  geom_point(aes(x = x1, y = x2, color = as.factor(region_num), pch = '.')) + 
  scale_color_discrete()

```


```{r cubist_test_1_region_num, echo=TRUE}

Cubist_region_num <- Cubist::cubist(x = grid_1[, c('x1', 'x2')], y = grid_1$region_num,
                                    committees = 1,
                                    control = Cubist::cubistControl(rules = 9))
summary(Cubist_region_num)
```


```{r Cubist_test_2, echo=TRUE}
# Create two features, x1 and x2
x1 <- seq(from = 1, to = 90, by = 1)
x2 <- seq(from = 10, to = 900, by = 10)

grid_1 <- expand.grid(x1, x2) # Turn x1 and x2 into a grid
colnames(grid_1) <- c("x1", "x2") # Rename columns

# Divide grid into 9 equally sized regions
grid_1$region_num <- rep(NA, length(x1) * length(x2))

grid_1$region_num[(grid_1$x1 >= 1 & grid_1$x1 <= 30) & (grid_1$x2 >= 10 & grid_1$x2 <= 300)] <- 10
grid_1$region_num[(grid_1$x1 >= 31 & grid_1$x1 <= 60) & (grid_1$x2 >= 10 & grid_1$x2 <= 300)] <- 20
grid_1$region_num[(grid_1$x1 >= 61 & grid_1$x1 <= 90) & (grid_1$x2 >= 10 & grid_1$x2 <= 300)] <- 30

grid_1$region_num[(grid_1$x1 >= 1 & grid_1$x1 <= 30) & (grid_1$x2 >= 310 & grid_1$x2 <= 600)] <- 40
grid_1$region_num[(grid_1$x1 >= 31 & grid_1$x1 <= 60) & (grid_1$x2 >= 310 & grid_1$x2 <= 600)] <- 50
grid_1$region_num[(grid_1$x1 >= 61 & grid_1$x1 <= 90) & (grid_1$x2 >= 310 & grid_1$x2 <= 600)] <- 60

grid_1$region_num[(grid_1$x1 >= 1 & grid_1$x1 <= 30) & (grid_1$x2 >= 610 & grid_1$x2 <= 900)] <- 70
grid_1$region_num[(grid_1$x1 >= 31 & grid_1$x1 <= 60) & (grid_1$x2 >= 610 & grid_1$x2 <= 900)] <- 80
grid_1$region_num[(grid_1$x1 >= 61 & grid_1$x1 <= 90) & (grid_1$x2 >= 610 & grid_1$x2 <= 900)] <- 90

table(grid_1$region_num, useNA = "always")

grid_1$response <- grid_1$region_num + rnorm(n = length(grid_1$region_num), mean = 0, sd = 2)
```

```{r plot_regions_2, echo=TRUE}
ggplot2::ggplot(data = grid_1) +
  geom_point(aes(x = x1, y = x2, color = response, pch = '.'))

```


```{r cubist_test_2_region_num, echo=TRUE}

Cubist_region_num <- Cubist::cubist(x = grid_1[, c('x1', 'x2')], y = grid_1$response,
                                    committees = 1,
                                    control = Cubist::cubistControl(rules = 9))
summary(Cubist_region_num)
```



```{r Cubist_test_3, echo=TRUE}
# Create two features, x1 and x2
x1 <- seq(from = 1, to = 90, by = 1)
x2 <- seq(from = 2, to = 92, by = 10)

grid_1 <- expand.grid(x1, x2) # Turn x1 and x2 into a grid
colnames(grid_1) <- c("x1", "x2") # Rename columns

grid_1$true_res <- 10 + (8 * grid_1$x1) + (3 * grid_1$x2)

grid_1$noise_res <- grid_1$true_res + rnorm(n = nrow(grid_1), mean = 0, sd = 150)
```

```{r plot_regions_3, echo=TRUE}
ggplot2::ggplot(data = grid_1) +
  geom_point(aes(x = x1, y = x2, color = true_res, pch = '.'))

```


```{r cubist_test_3_region_num, echo=TRUE}

Cubist_region_num <- Cubist::cubist(x = grid_1[, c('x1', 'x2')], y = grid_1$noise_res,
                                    committees = 1,
                                    control = Cubist::cubistControl(rules = 9))
summary(Cubist_region_num)

Cubist_predict_noise_res <- stats::predict(object = Cubist_region_num, newdata = grid_1, na.action = na.pass, neighbors = 0)

Cubist_explore_noise <- data.frame(x1 = grid_1$x1,
                                   x2 = grid_1$x2,
                                   true_res = grid_1$true_res,
                                   noise_res = grid_1$noise_res,
                                   pred_noise_res = Cubist_predict_noise_res,
                                   resid = grid_1$noise_res - Cubist_predict_noise_res)
```




```{r Cubist_test_4, echo=TRUE}
# Create two features, x1 and x2
x1 <- seq(from = 1, to = 90, by = 1)
x2 <- seq(from = 10, to = 900, by = 10)

grid_1 <- expand.grid(x1, x2) # Turn x1 and x2 into a grid
colnames(grid_1) <- c("x1", "x2") # Rename columns

# Divide grid into 9 equally sized regions
grid_1$region_num <- rep(NA, length(x1) * length(x2))

grid_1$region_num[(grid_1$x1 >= 1 & grid_1$x1 <= 30) & (grid_1$x2 >= 10 & grid_1$x2 <= 300)] <- 1
grid_1$region_num[(grid_1$x1 >= 31 & grid_1$x1 <= 60) & (grid_1$x2 >= 10 & grid_1$x2 <= 300)] <- 2
grid_1$region_num[(grid_1$x1 >= 61 & grid_1$x1 <= 90) & (grid_1$x2 >= 10 & grid_1$x2 <= 300)] <- 3

grid_1$region_num[(grid_1$x1 >= 1 & grid_1$x1 <= 30) & (grid_1$x2 >= 310 & grid_1$x2 <= 600)] <- 4
grid_1$region_num[(grid_1$x1 >= 31 & grid_1$x1 <= 60) & (grid_1$x2 >= 310 & grid_1$x2 <= 600)] <- 5
grid_1$region_num[(grid_1$x1 >= 61 & grid_1$x1 <= 90) & (grid_1$x2 >= 310 & grid_1$x2 <= 600)] <- 6

grid_1$region_num[(grid_1$x1 >= 1 & grid_1$x1 <= 30) & (grid_1$x2 >= 610 & grid_1$x2 <= 900)] <- 7
grid_1$region_num[(grid_1$x1 >= 31 & grid_1$x1 <= 60) & (grid_1$x2 >= 610 & grid_1$x2 <= 900)] <- 8
grid_1$region_num[(grid_1$x1 >= 61 & grid_1$x1 <= 90) & (grid_1$x2 >= 610 & grid_1$x2 <= 900)] <- 9

table(grid_1$region_num, useNA = "always")

grid_1$response <- rep(NA, length(grid_1$x1))

grid_1$response[grid_1$region_num == 1] <- 10 + (0 * grid_1$x1[grid_1$region_num == 1]) + (0 * grid_1$x2[grid_1$region_num == 1])
grid_1$response[grid_1$region_num == 2] <- 00 + (2 * grid_1$x1[grid_1$region_num == 2]) + (0 * grid_1$x2[grid_1$region_num == 2])
grid_1$response[grid_1$region_num == 3] <- 00 + (0 * grid_1$x1[grid_1$region_num == 3]) + (2 * grid_1$x2[grid_1$region_num == 3])
grid_1$response[grid_1$region_num == 4] <- 00 + (2 * grid_1$x1[grid_1$region_num == 4]) + (2 * grid_1$x2[grid_1$region_num == 4])
grid_1$response[grid_1$region_num == 5] <- 00 + (2 * grid_1$x1[grid_1$region_num == 5]) + (-2 * grid_1$x2[grid_1$region_num == 5])
grid_1$response[grid_1$region_num == 6] <- 00 + (-2 * grid_1$x1[grid_1$region_num == 6]) + (2 * grid_1$x2[grid_1$region_num == 6])
grid_1$response[grid_1$region_num == 7] <- 15 + (2 * grid_1$x1[grid_1$region_num == 7]) + (3 * grid_1$x2[grid_1$region_num == 7])
grid_1$response[grid_1$region_num == 8] <- 8 + (2 * grid_1$x1[grid_1$region_num == 8]) + (-3 * grid_1$x2[grid_1$region_num == 8])
grid_1$response[grid_1$region_num == 9] <- 00 + (2 * grid_1$x1[grid_1$region_num == 9]) + (2 * grid_1$x2[grid_1$region_num == 9])
```

```{r plot_regions_4, echo=TRUE}
ggplot2::ggplot(data = grid_1) +
  geom_point(aes(x = x1, y = x2, color = response, pch = '.'))

```


```{r cubist_test_4_region_num, echo=TRUE}

Cubist_region_num <- Cubist::cubist(x = grid_1[, c('x1', 'x2')], y = grid_1$response,
                                    committees = 1,
                                    control = Cubist::cubistControl(rules = 9))
summary(Cubist_region_num)
```



```{r Cubist_test_5, echo=TRUE}
# Create two features, x1 and x2
x1 <- seq(from = 1, to = 90, by = 1)
x2 <- seq(from = 10, to = 900, by = 10)

grid_1 <- expand.grid(x1, x2) # Turn x1 and x2 into a grid
colnames(grid_1) <- c("x1", "x2") # Rename columns

# Divide grid into 9 equally sized regions
grid_1$region_num <- rep(NA, length(x1) * length(x2))

grid_1$region_num[(grid_1$x1 >= 1 & grid_1$x1 <= 30) & (grid_1$x2 >= 10 & grid_1$x2 <= 300)] <- 1
grid_1$region_num[(grid_1$x1 >= 31 & grid_1$x1 <= 60) & (grid_1$x2 >= 10 & grid_1$x2 <= 300)] <- 2
grid_1$region_num[(grid_1$x1 >= 61 & grid_1$x1 <= 90) & (grid_1$x2 >= 10 & grid_1$x2 <= 300)] <- 3

grid_1$region_num[(grid_1$x1 >= 1 & grid_1$x1 <= 30) & (grid_1$x2 >= 310 & grid_1$x2 <= 600)] <- 4
grid_1$region_num[(grid_1$x1 >= 31 & grid_1$x1 <= 60) & (grid_1$x2 >= 310 & grid_1$x2 <= 600)] <- 5
grid_1$region_num[(grid_1$x1 >= 61 & grid_1$x1 <= 90) & (grid_1$x2 >= 310 & grid_1$x2 <= 600)] <- 6

grid_1$region_num[(grid_1$x1 >= 1 & grid_1$x1 <= 30) & (grid_1$x2 >= 610 & grid_1$x2 <= 900)] <- 7
grid_1$region_num[(grid_1$x1 >= 31 & grid_1$x1 <= 60) & (grid_1$x2 >= 610 & grid_1$x2 <= 900)] <- 8
grid_1$region_num[(grid_1$x1 >= 61 & grid_1$x1 <= 90) & (grid_1$x2 >= 610 & grid_1$x2 <= 900)] <- 9

table(grid_1$region_num, useNA = "always")

grid_1$response <- rep(NA, length(grid_1$x1))

grid_1$response[grid_1$region_num == 1] <- 10 + (0 * grid_1$x1[grid_1$region_num == 1]) + (0 * grid_1$x2[grid_1$region_num == 1])
grid_1$response[grid_1$region_num == 2] <- 00 + (2 * grid_1$x1[grid_1$region_num == 2]) + (0 * grid_1$x2[grid_1$region_num == 2])
grid_1$response[grid_1$region_num == 3] <- 00 + (0 * grid_1$x1[grid_1$region_num == 3]) + (2 * grid_1$x2[grid_1$region_num == 3])
grid_1$response[grid_1$region_num == 4] <- 00 + (2 * grid_1$x1[grid_1$region_num == 4]) + (2 * grid_1$x2[grid_1$region_num == 4])
grid_1$response[grid_1$region_num == 5] <- 00 + (2 * grid_1$x1[grid_1$region_num == 5]) + (-2 * grid_1$x2[grid_1$region_num == 5])
grid_1$response[grid_1$region_num == 6] <- 00 + (-2 * grid_1$x1[grid_1$region_num == 6]) + (2 * grid_1$x2[grid_1$region_num == 6])
grid_1$response[grid_1$region_num == 7] <- 15 + (2 * grid_1$x1[grid_1$region_num == 7]) + (3 * grid_1$x2[grid_1$region_num == 7])
grid_1$response[grid_1$region_num == 8] <- 8 + (2 * grid_1$x1[grid_1$region_num == 8]) + (-3 * grid_1$x2[grid_1$region_num == 8])
grid_1$response[grid_1$region_num == 9] <- 00 + (2 * grid_1$x1[grid_1$region_num == 9]) + (2 * grid_1$x2[grid_1$region_num == 9])

grid_1$response <- grid_1$response + rnorm(n = length(grid_1$response), mean = 0, sd = 10)
```

```{r plot_regions_5, echo=TRUE}
ggplot2::ggplot(data = grid_1) +
  geom_point(aes(x = x1, y = x2, color = response, pch = '.'))

```


```{r cubist_test_5_region_num, echo=TRUE}

Cubist_region_num <- Cubist::cubist(x = grid_1[, c('x1', 'x2')], y = grid_1$response,
                                    committees = 1,
                                    control = Cubist::cubistControl(rules = 9))
summary(Cubist_region_num)
```



```{r Cubist_test_6, echo=TRUE}
# Create two features, x1 and x2
x1 <- seq(from = 1, to = 90, by = 1)
x2 <- seq(from = 10, to = 900, by = 10)

grid_1 <- expand.grid(x1, x2) # Turn x1 and x2 into a grid
colnames(grid_1) <- c("x1", "x2") # Rename columns

grid_1$response <- 1 + ((2 * grid_1$x1) ^ 3)

```

```{r plot_regions_6, echo=TRUE}
ggplot2::ggplot(data = grid_1) +
  geom_point(aes(x = x1, y = x2, color = response, pch = '.'))

```


```{r cubist_test_6_region_num, echo=TRUE}

Cubist_response_squared <- Cubist::cubist(x = grid_1[, c('x1', 'x2')], y = grid_1$response,
                                          committees = 1,
                                          control = Cubist::cubistControl(rules = 9))
summary(Cubist_response_squared)

plot(grid_1$x1, grid_1$response)
#abline(v = c(10, 17, 28, 45, 56, 67, 78))
```


# Cubist Exploration with MODIS SST Data
## Prep Workspace
```{r prep_workspace_SST, include=FALSE}
# Import necessary packages
require(ggplot2)
require(dplyr)
require(RColorBrewer)
require(circular)
require(ggmap)
require(raster)
require(rasterVis)
require(caret)
require(partykit)
require(randomForest)
require(stringr)
require(stringi)
require(raster)
require(sp)
require(rgdal)
require(rasterVis)
require(rpart)
require(rpart.plot)
require(scales)
require(gplots)

ggplot <- function(...) {ggplot2::ggplot(...) + theme_bw()}

# Define secant function
secant.deg <- function(x) {1 / (cos(circular::rad(x)))}

# Source own functions
# Define direwctory where functions are for each operating system

if (Sys.info()["sysname"] == 'Windows') {
  fun.dir <- 'D:/matchups/r-projects/Matchup_R_Scripts/Functions/'
} else if (Sys.info()["sysname"] == 'Linux') {
  fun.dir <- '/home/ckk/Projects/Matchup_R_Scripts/Functions/'
}

fun.file <- paste0(fun.dir, 'common_functions.R')

source(file = fun.file,
  local = FALSE, echo = FALSE, verbose = FALSE)
rm(fun.dir, fun.file)


# Load data
# For 787
linux_dir <- '~/Projects/Matchup_R_Scripts/Results/objects/'
# For Laptop
#linux_dir <- '~/Projects/Matchup_R_Scripts/'
linux_file <- 'MODIS_Aqua_GSFC_ALL_Class_6.4.1_ao_2017_04_12_with_ancillary.Rdata'
AQUA_file <- paste0(linux_dir, linux_file)

if (!file.exists(AQUA_file)) {
    stop('Input file does not exist')
  } else {
    load(AQUA_file, verbose = TRUE)
    AQUA <- MODIS_Aqua_GSFC_ALL_Class_6.4.1_ao_2017_04_12
  }

rm(linux_dir, linux_file, AQUA_file)
rm(MODIS_Aqua_GSFC_ALL_Class_6.4.1_ao_2017_04_12)

set.seed(108)
```

## Feature Exploration
```{r prep_data, echo=TRUE}
# Turn POSIXct objects to characters bc dplyr doesn't support POSIXct
AQUA$sat.timedate <- as.character(AQUA$sat.timedate)
AQUA$buoy.timedate <- as.character(AQUA$buoy.timedate)

# Apply basic filtering
AQUA <- dplyr::tbl_df(AQUA) %>%
  dplyr::filter(solz >= 90) %>%
  dplyr::filter(qsst == 0 | qsst == 1 | qsst == 2) # 1130520 Matchups

# Now grab only variables that may be used to determine retrieval accuracy and make some new variables (i.e. x1, x2, x3)
# Create df of features
orig <- dplyr::tbl_df(AQUA) %>%
  dplyr::mutate(T_11 = cen.11000,
    T_12 = cen.12000,
    band.diff = T_11 - T_12,
    ref_SST = cen.ref.type.1.SST,
    x2 = band.diff * ref_SST,
    x3 = ((secant.deg(satz) - 1) * band.diff),
    lat = buoy.lat,
    lon = buoy.lon,
    month = lubridate::month(as.POSIXct(buoy.timedate)),
    sd11 = sd.11000,
    sd12 = sd.12000,
    range11 = max.11000 - min.11000,
    range12 = max.12000 - min.12000,
    diff.med.min11 = med.11000 - min.11000,
    diff.med.min12 = med.12000 - min.12000,
    qsst = qsst,
    buoy.sst = buoy.sst,
    cell5deg = cell5deg,
    buoy.timedate = buoy.timedate,
    td_estimate = cen.ref.type.1.SST - cen.11000,
    cen.sst = cen.sst,
    pseudo.resid.SMR = cen.sst - cen.ref.type.1.SST,
    td_actual = T_11 - buoy.sst,
    SST.resid.SMB = cen.sst - (buoy.sst - 0.17)) %>% # SMB = sat minus buoy - also debias buoy.sst by turning buoy.sst into a skin measurement
  dplyr::select(T_11, T_12, band.diff, ref_SST, x2, x3, satz, lon, lat, month, sd11, sd12, range11, range12, diff.med.min11, diff.med.min12,
    qsst, buoy.sst, cell5deg, cen.sst, td_estimate, td_actual, SST.resid.SMB)

```

```{r create_temp_SSES_dataframe, echo=TRUE}

set.seed(108)
index <- sample(1:nrow(orig), 50000, replace = FALSE)
uuu <- orig[index, ]

td_loess <- loess(td_estimate ~ x2, data = uuu, span = 0.4)
orig$td_resid <- stats::predict(td_loess, newdata = orig$x2)

# Some td_resid may be NA because of domain restrictions on loess - filter them out
orig <- dplyr::tbl_df(orig) %>%
  dplyr::filter(!is.na(td_resid))
orig <- as.data.frame(orig)

SSES_df_temp <- dplyr::tbl_df(orig) %>%
  dplyr::select(td_resid,
                x2,
                satz,
                sd11,
                ref_SST,
                lat,
                month,
                td_estimate,
                SST.resid.SMB)


```

```{r correlogram_of_features, echo=TRUE}
# Take the correlation matrix
cors_mat_f <- as.matrix(cor(SSES_df_temp))
cors_df_f <- as.matrix(cor(SSES_df_temp))

# Format the data for the plot
xval <- formatC(cors_mat_f, format = "f", digits = 2)
pal <- colorRampPalette(c(rgb(0.96,0.96,1), rgb(0.1,0.1,0.9)), space = "rgb")

 # Plot the matrix
corrgram <- gplots::heatmap.2(cors_mat_f,
                              Rowv = FALSE, Colv = FALSE,
                              dendrogram = "none",
                              main = "Correlogram",
                              xlab = "Columns", ylab = "Rows",
                              col = pal,
                              tracecol = "#303030", trace = "none",
                              cellnote = xval, notecol = "black", notecex = 0.8,
                              keysize = 1.5, margins = c(5, 5))

```


```{r correlogram_of_orig, echo=TRUE}
# Take the correlation matrix
cors_mat_o <- as.matrix(cor(orig))
cors_df_o <- as.matrix(cor(orig))

# Format the data for the plot
xval <- formatC(cors_mat_o, format = "f", digits = 2)
pal <- colorRampPalette(c(rgb(0.96,0.96,1), rgb(0.1,0.1,0.9)), space = "rgb")

 # Plot the matrix
corrgram <- gplots::heatmap.2(cors_mat_o,
                              Rowv = FALSE, Colv = FALSE,
                              dendrogram = "none",
                              main = "Correlogram",
                              xlab = "Columns", ylab = "Rows",
                              col = pal,
                              tracecol = "#303030", trace = "none",
                              cellnote = xval, notecol = "black", notecex = 0.8,
                              keysize = 1.5, margins = c(5, 5))

```

## Cubist Exploration

```{r create_train_test_sets, echo=TRUE}
# Take sample of orig
len_samp <- 200000
index <- sample(1:nrow(SSES_df_temp), len_samp, replace = FALSE)
SSES_df_temp_samp <- SSES_df_temp[index, ]

# Divide data into training and validation sets
prop_train <- .7
len_train <- floor(prop_train * nrow(SSES_df_temp_samp))
index <- sample(1:nrow(SSES_df_temp_samp), len_train, replace = FALSE)
SSES_df_temp_train <- SSES_df_temp_samp[index, ]
SSES_df_temp_test <- SSES_df_temp_samp[-index, ]
```


```{r Cubist, echo=TRUE}
# Statistics of train data
cat('mean of train SST residuals: ')
mean(SSES_df_temp_train$SST.resid.SMB)
paste('sd of train SST residuals: ')
sd(SSES_df_temp_train$SST.resid.SMB)

Cubist_rules_expl <- Cubist::cubist(x = SSES_df_temp_train[, c('td_resid', 'x2', 'satz', 'ref_SST', 'lat', 'month', 'sd11')], y = SSES_df_temp$SST.resid.SMB,
                                    committees = 1,
                                    control = Cubist::cubistControl(rules = 28,
                                                                    unbiased = FALSE,
                                                                    extrapolation = 100,
                                                                    label = 'SST Residual',
                                                                    seed = 108))
Cubist_rules_explr

dotplot(Cubist_rules_expl, what = 'splits')
dotplot(Cubist_rules_expl, what = 'coefs')

# Evaluate the tree
## Use the tree to predict
### Train set
N_correction_neighbors <- 8 # Must be between 0 and 9

Cubist_rules_train_vals <- stats::predict(object = Cubist_rules_expl, newdata = SSES_df_temp_train, na.action = na.pass, neighbors = N_correction_neighbors)

### Train set
cat('TRAIN SET: ')
cat('mean of residual predictions: ')
mean(Cubist_rules_train_vals)
cat('sd of residual predictions: ')
sd(Cubist_rules_train_vals)
RMSE_train_cubist <- caret::RMSE(Cubist_rules_train_vals, SSES_df_temp_train$SST.resid.SMB)
cat('RMSE train: ')
RMSE_train_cubist
MAE_train_cubist <- mean(abs(Cubist_rules_train_vals - SSES_df_temp_train$SST.resid.SMB))
cat('MAE train: ')
MAE_train_cubist
cat('IQR of model residuals: ')
IQR(Cubist_rules_train_vals - SSES_df_temp_train$SST.resid.SMB)
cat('median of model residuals: ')
median(Cubist_rules_train_vals - SSES_df_temp_train$SST.resid.SMB)
cat('Correlation of model predictions: ')
cor(Cubist_rules_train_vals, SSES_df_temp_train$SST.resid.SMB)
cat('Index of Agreement of model predictions: ')
hydroGOF::d(Cubist_rules_train_vals, SSES_df_temp_train$SST.resid.SMB)

### Test set
cat('TEST SET: ')
cat('mean of residual predictions: ')
mean(Cubist_rules_test_vals)
cat('sd of residual predictions: ')
sd(Cubist_rules_test_vals)
RMSE_test_cubist <- caret::RMSE(Cubist_rules_test_vals, SSES_df_temp_train_test$SST.resid.SMB)
cat('RMSE test: ')
RMSE_test_cubist
MAE_test_cubist <- mean(abs(Cubist_rules_test_vals - SSES_df_temp_train_test$SST.resid.SMB))
cat('MAE test: ')
MAE_test_cubist
cat('IQR of model residuals: ')
IQR(Cubist_rules_test_vals - SSES_df_temp_train_test$SST.resid.SMB)
cat('median of model residuals: ')
median(Cubist_rules_test_vals - SSES_df_temp_train_test$SST.resid.SMB)
cat('Correlation of model predictions')
cor(Cubist_rules_test_vals, SSES_df_temp_train_test$SST.resid.SMB)
cat('Index of Agreement of model predictions')
hydroGOF::d(Cubist_rules_test_vals, SSES_df_temp_train$SST.resid.SMB)

# Plot
ccc <- RColorBrewer::brewer.pal(n = 9, 'YlOrRd')
ccc <- ccc[3:9]
breaks <- c(0, 10, 25, 50, 100, 500, 1000, 2500, 5000, 10000, Inf)

yyy <- data.frame(Y = Cubist_rules_test_vals, X = SSES_df_temp_train_test$SST.resid.SMB)

ccc <- colorRampPalette(ccc)(length(breaks) - 1)

ggplot2::ggplot(data = yyy, aes(X, Y, fill = cut(..count.., c(0, 10, 25, 50, 100, 500, 1000, 2500, 5000, 10000, Inf)))) +
  geom_bin2d(bins = 75) +
  scale_fill_manual(values = ccc, '# of Retrievals') +
  geom_abline(slope = 1, intercept = 0, color = 'black') +
  labs(x = 'Actual Residual (deg C)', y = 'Predicted Residual (deg C)') +
  ggsave('Cubist_predictions_vs_actual_residual_2d_histogram.pdf', device = 'pdf', width = 8, height = 6, units = 'in') + 
  ggsave('Cubist_predictions_vs_actual_residual_2d_histogram.png', device = 'png', width = 8, height = 6, units = 'in')

residual_fit_cubist <- lm(Y ~ X, data = yyy)
residual_fit_cubist

```
